# Site settings
title: Dustin & Cali & Zut Alors!
email: tinney@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An Epic Adventure. Between 2 friends, life partners and adventure seekers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zutroadtrip.com" # the base hostname & protocol for your site
twitter_username: dustintinney
github_username:  tinney

# Build settings
markdown: kramdown
